In [35]:
import numpy as np
import pandas as pd

In [36]:
SOURCE, TARGET, RATING, TIME = 'SOURCE', 'TARGET', 'RATING', 'TIME'
df = pd.read_csv('soc-sign-bitcoinotc.csv', names=[SOURCE,TARGET,RATING,TIME])

In [37]:
df = df.loc[(df[RATING] >= 8)]
df = df[[SOURCE, TARGET, RATING]]
df[RATING] = df[RATING].apply(lambda rate: rate/10.0)

In [38]:
nodes = list(set(df.SOURCE.append(df.TARGET)))
nodes = sorted(nodes)

In [41]:
adj_m = pd.DataFrame(columns=nodes)

In [42]:
n_pointing_to_me = dict()
for target, group_itens in df.groupby([TARGET]):
    n_pointing_to_me[target] = len(group_itens)

In [44]:
for source in nodes:
    tmp = df.loc[(df[SOURCE] == source)]
    target_list, rating_list = tmp.TARGET, tmp.RATING
    adj_line = [0] * len(nodes)
    for t, r in zip(target_list, rating_list):
        target_index = nodes.index(t)
        adj_line[target_index] = r/n_pointing_to_me[t]
    adj_m.loc[source] = adj_line

In [46]:
a = adj_m.values

b = (float(1)/float(len(nodes))) * np.matrix([[1] * len(nodes) for i in range(len(nodes))])

m = (0.85 * a) + (0.15 * b)

v = (float(1)/float(len(nodes))) * np.matrix([[1] for i in range(len(nodes))])

In [47]:
def pagerank(v):
    global count
    if sum(abs(m*v-v)) > 0.001:
        count += 1
        print('count: ', count)
        print(m*v)
        print('sum(abs(m*v-v)): ', sum(abs(m*v-v)))
        return pagerank(m*v)
    else:
        count += 1
        print('count: ', count)
        print(m*v)
        print('sum(abs(m*v-v)): ', sum(abs(m*v-v)))
        return m*v

In [48]:
count = 0
result = pagerank(v)
print('Sorted result: ', sorted(result, reverse=True))

count:  1
[[0.00399364]
 [0.00347104]
 [0.00016393]
 [0.00161046]
 [0.001449  ]
 [0.00016393]
 [0.00016393]
 [0.00018605]
 [0.00082674]
 [0.00147082]
 [0.00016393]
 [0.00018384]
 [0.00024815]
 [0.00016393]
 [0.00287562]
 [0.00016393]
 [0.00016393]
 [0.00016393]
 [0.00046032]
 [0.00047359]
 [0.00150695]
 [0.00032026]
 [0.00016393]
 [0.0010929 ]
 [0.00029542]
 [0.0010929 ]
 [0.00183607]
 [0.00016393]
 [0.00202186]
 [0.00018163]
 [0.0009071 ]
 [0.00016393]
 [0.00192896]
 [0.00041166]
 [0.00016393]
 [0.00047359]
 [0.00016393]
 [0.0010929 ]
 [0.00117587]
 [0.00111501]
 [0.0010929 ]
 [0.00025751]
 [0.00016393]
 [0.00016393]
 [0.00016393]
 [0.00041166]
 [0.00018974]
 [0.00016393]
 [0.00016393]
 [0.00089472]
 [0.00018163]
 [0.0010929 ]
 [0.00016393]
 [0.00016393]
 [0.00217049]
 [0.00062842]
 [0.00016393]
 [0.0009071 ]
 [0.001     ]
 [0.00018605]
 [0.00016393]
 [0.00028337]
 [0.00016393]
 [0.00047359]
 [0.00111059]
 [0.001     ]
 [0.00016393]
 [0.00053552]
 [0.00016393]
 [0.00016393]
 [0.001092

[[3.75218157e-04]
 [2.09279099e-04]
 [2.87471540e-05]
 [2.15151496e-04]
 [8.44450197e-05]
 [2.87471540e-05]
 [2.87471540e-05]
 [3.84800398e-05]
 [1.72013599e-04]
 [1.58593194e-04]
 [2.87471540e-05]
 [3.75067512e-05]
 [3.94859989e-05]
 [2.87471540e-05]
 [3.23671540e-04]
 [2.87471540e-05]
 [2.87471540e-05]
 [2.87471540e-05]
 [6.51220425e-05]
 [4.25787289e-05]
 [1.90516015e-04]
 [5.74025201e-05]
 [2.87471540e-05]
 [5.72082532e-04]
 [3.83312615e-05]
 [5.73362874e-05]
 [8.02075941e-05]
 [2.87471540e-05]
 [4.08453624e-04]
 [3.65334627e-05]
 [5.16184607e-05]
 [2.87471540e-05]
 [8.30665075e-05]
 [1.39463135e-04]
 [2.87471540e-05]
 [3.82768651e-05]
 [2.87471540e-05]
 [5.72082532e-04]
 [5.98897613e-05]
 [6.42583879e-04]
 [6.31313562e-04]
 [4.06792039e-05]
 [2.87471540e-05]
 [2.87471540e-05]
 [2.87471540e-05]
 [4.71448792e-05]
 [2.95412966e-05]
 [2.87471540e-05]
 [2.87471540e-05]
 [1.09378978e-04]
 [3.65334627e-05]
 [5.72082532e-04]
 [2.87471540e-05]
 [2.87471540e-05]
 [1.03968958e-03]
 [1.037930

count:  16
[[1.05582411e-04]
 [6.21040658e-05]
 [9.60441654e-06]
 [5.60289918e-05]
 [2.66494103e-05]
 [9.60441654e-06]
 [9.60441654e-06]
 [1.20571182e-05]
 [4.14428350e-05]
 [4.40064433e-05]
 [9.60441654e-06]
 [1.18118481e-05]
 [1.24552306e-05]
 [9.60441654e-06]
 [8.63829354e-05]
 [9.60441654e-06]
 [9.60441654e-06]
 [9.60441654e-06]
 [1.92749443e-05]
 [1.40404546e-05]
 [5.20112453e-05]
 [1.69876969e-05]
 [9.60441654e-06]
 [2.25320717e-04]
 [1.23875907e-05]
 [1.88977192e-05]
 [2.63323614e-05]
 [9.60441654e-06]
 [1.08169867e-04]
 [1.15665779e-05]
 [1.70390587e-05]
 [9.60441654e-06]
 [2.72616916e-05]
 [3.26243691e-05]
 [9.60441654e-06]
 [1.27021841e-05]
 [9.60441654e-06]
 [2.25320717e-04]
 [1.97277621e-05]
 [2.54042037e-04]
 [2.50906038e-04]
 [1.27719877e-05]
 [9.60441654e-06]
 [9.60441654e-06]
 [9.60441654e-06]
 [1.51129463e-05]
 [9.86256383e-06]
 [9.60441654e-06]
 [9.60441654e-06]
 [3.16956808e-05]
 [1.15665779e-05]
 [2.25320717e-04]
 [9.60441654e-06]
 [9.60441654e-06]
 [4.23648153e-04]

[[5.50544853e-05]
 [3.25654868e-05]
 [5.08750512e-06]
 [2.89700727e-05]
 [1.40413196e-05]
 [5.08750512e-06]
 [5.08750512e-06]
 [6.35329892e-06]
 [2.10963986e-05]
 [2.28294695e-05]
 [5.08750512e-06]
 [6.22671954e-06]
 [6.56624863e-06]
 [5.08750512e-06]
 [4.43496855e-05]
 [5.08750512e-06]
 [5.08750512e-06]
 [5.08750512e-06]
 [1.01172283e-05]
 [7.42494667e-06]
 [2.71000781e-05]
 [8.91322458e-06]
 [5.08750512e-06]
 [1.23671727e-04]
 [6.52967278e-06]
 [9.99181429e-06]
 [1.39152616e-05]
 [5.08750512e-06]
 [5.33713446e-05]
 [6.10014016e-06]
 [9.01095246e-06]
 [5.08750512e-06]
 [1.44056925e-05]
 [1.65065664e-05]
 [5.08750512e-06]
 [6.72227484e-06]
 [5.08750512e-06]
 [1.23671727e-04]
 [1.04298487e-05]
 [1.38589880e-04]
 [1.38789443e-04]
 [6.73055347e-06]
 [5.08750512e-06]
 [5.08750512e-06]
 [5.08750512e-06]
 [7.97955347e-06]
 [5.22373593e-06]
 [5.08750512e-06]
 [5.08750512e-06]
 [1.65934806e-05]
 [6.10014016e-06]
 [1.23671727e-04]
 [5.08750512e-06]
 [5.08750512e-06]
 [2.55807745e-04]
 [1.415744

sum(abs(m*v-v)):  [[0.0021226]]
count:  27
[[2.58971430e-05]
 [1.53566708e-05]
 [2.40911932e-06]
 [1.36077748e-05]
 [6.63374784e-06]
 [2.40911932e-06]
 [2.40911932e-06]
 [3.00275674e-06]
 [9.87924985e-06]
 [1.07070804e-05]
 [2.40911932e-06]
 [2.94339300e-06]
 [3.10386317e-06]
 [2.40911932e-06]
 [2.06830417e-05]
 [2.40911932e-06]
 [2.40911932e-06]
 [2.40911932e-06]
 [4.77381201e-06]
 [3.51302013e-06]
 [1.27525020e-05]
 [4.20506920e-06]
 [2.40911932e-06]
 [5.98062930e-05]
 [3.07931434e-06]
 [4.72702179e-06]
 [6.58134376e-06]
 [2.40911932e-06]
 [2.40255600e-05]
 [2.88402926e-06]
 [4.26344130e-06]
 [2.40911932e-06]
 [6.81313401e-06]
 [7.72096331e-06]
 [2.40911932e-06]
 [3.18175348e-06]
 [2.40911932e-06]
 [5.98062930e-05]
 [4.93404812e-06]
 [6.70893013e-05]
 [6.71051382e-05]
 [3.18105693e-06]
 [2.40911932e-06]
 [2.40911932e-06]
 [2.40911932e-06]
 [3.77271914e-06]
 [2.47350550e-06]
 [2.40911932e-06]
 [2.40911932e-06]
 [7.82034332e-06]
 [2.88402926e-06]
 [5.98062930e-05]
 [2.40911932e-06]
 [2

[[1.39394877e-05]
 [8.27226948e-06]
 [1.29966864e-06]
 [7.32132761e-06]
 [3.57573988e-06]
 [1.29966864e-06]
 [1.29966864e-06]
 [1.61886265e-06]
 [5.31130110e-06]
 [5.75948360e-06]
 [1.29966864e-06]
 [1.58694325e-06]
 [1.67344852e-06]
 [1.29966864e-06]
 [1.11096594e-05]
 [1.29966864e-06]
 [1.29966864e-06]
 [1.29966864e-06]
 [2.57212889e-06]
 [1.89458200e-06]
 [6.86477277e-06]
 [2.26561810e-06]
 [1.29966864e-06]
 [3.25535965e-05]
 [1.65853033e-06]
 [2.54918918e-06]
 [3.54880561e-06]
 [1.29966864e-06]
 [1.27039061e-05]
 [1.55502385e-06]
 [2.29928507e-06]
 [1.29966864e-06]
 [3.67375766e-06]
 [4.14979215e-06]
 [1.29966864e-06]
 [1.71617549e-06]
 [1.29966864e-06]
 [3.25535965e-05]
 [2.66079166e-06]
 [3.66802991e-05]
 [3.63763684e-05]
 [1.71497962e-06]
 [1.29966864e-06]
 [1.29966864e-06]
 [1.29966864e-06]
 [2.03409636e-06]
 [1.33437755e-06]
 [1.29966864e-06]
 [1.29966864e-06]
 [4.21187887e-06]
 [1.55502385e-06]
 [3.25535965e-05]
 [1.29966864e-06]
 [1.29966864e-06]
 [6.29756822e-05]
 [3.580754